#!/bin/zsh
# screenshot a region using maim and upload to 0x0.st

pb() {
	curl -F file=@- 'https://0x0.st/'
}

file=$(mktemp /tmp/screenshot_XXXXXX.png)
maim --select --hidecursor $file
success=$?
if [ $success -eq 0 ]; then
	cat $file | pb | xsel -b
	notify-send -t 1000 'Screenshot uploaded.' -i '/usr/share/icons/Arc/apps/symbolic/applets-screenshooter-symbolic.svg'
fi
rm $file
